library(data.table)
library(magrittr)

study_tcga_map <- data.table()[,
    c('study', 'cancer_type') := rbindlist(.(
        .('ALL_Ebinger_2016', NA),
        .('AML_Galen_2019', 'LAML'),
        .('AML_Wu_2020', 'LAML'),
        .('AUTONOMIC_GANGLIA_Kinker_2020', NA),
        .('BILIARY_TRACT_Kinker_2020', 'LIHC'),
        .('BONE_Kinker_2020', NA),
        .('Breast_Chung_2017', 'BRCA'),
        .('Breast_Gao_2021', 'BRCA'),
        .('Breast_Jordan_2016', 'BRCA'),
        .('Breast_Karaayvas_2018', 'BRCA'),
        .('BREAST_Kinker_2020', 'BRCA'),
        .('Breast_Pal_2021', 'BRCA'),
        .('Breast_Qian_2020', 'BRCA'),
        .('CENTRAL_NERVOUS_SYSTEM_Kinker_2020', NA),
        .('CML_Giustacchini_2017', NA),
        .('Colon_Li_2017', 'COAD'),
        .('Colon_Li_2017', 'READ'),
        .('CRC_Lee_2020', 'COAD'),
        .('CRC_Lee_2020', 'READ'),
        .('ENDOMETRIUM_Kinker_2020', 'UCEC'),
        .('Ependymoma_Gojo_2020', NA),
        .('ESCC_Yao_2020', 'ESCA_ESCC'),
        .('Ewing_CellLines_Aynaud_2020', NA),
        .('Ewing_PDX_Aynaud_2020', NA),
        .('GBM_cell_lines', 'GBM_IDH-WT'),
        .('GBM_mouse_Unpublished', 'GBM_IDH-WT'),
        .('Glioblastoma_Couturier_2020', 'GBM_IDH-WT'),
        .('Glioblastoma_Darmanis_2017', 'GBM_IDH-WT'),
        .('Glioblastoma_Wang_2019', 'GBM_IDH-WT'),
        .('Glioma_Filbin_2018', NA), # H3-K27M mutant - a kind of HGG that's not GBM
        .('Glioma_Neftel_2019', 'GBM_IDH-WT'),
        .('Glioma_Tirosh_2016', 'LGG_oligo'),
        .('Glioma_Venteicher_2017', 'LGG_astro'),
        .('Glioma_Yuan_2018', 'GBM_IDH-WT'), # 7 GBMs and 1 grade III astrocytoma (TCGA LGG does include plenty of Grade 3 LGGs)
        .('Glioma_Yuan_2018', 'LGG_astro'),
        .('HCC_Sun_2021', 'LIHC'),
        .('HGSOC_Izar_2020', 'OV'),
        .('HNSCC_Puram_2017', 'HNSC'),
        .('IPMN_Franses_2017', NA), # CTCs
        .('KIDNEY_Kinker_2020', 'KICH'),
        .('KIDNEY_Kinker_2020', 'KIRC'),
        .('KIDNEY_Kinker_2020', 'KIRP'),
        .('LARGE_INTESTINE_Kinker_2020', 'COAD'),
        .('LARGE_INTESTINE_Kinker_2020', 'READ'),
        .('Leukemia_Caron_2020', NA), # ALL
        .('LIVER_Kinker_2020', 'LIHC'),
        .('Liver_Ma_2019', 'LIHC'),
        .('Liver_Ma_2019', 'CHOL'),
        .('LiverMets_Massalha_2020', NA), # these are either CRC metastases to the liver or intra-hepatic cholangiocarcinoma
        .('LSCC_Unpublished', 'HNSC'),
        .('Lung_Kim_2020', 'LUAD'),
        .('LUNG_Kinker_2020', 'LUAD'),
        .('LUNG_Kinker_2020', 'LUSC'),
        .('Lung_Laughney_2020', 'LUAD'),
        .('Lung_Qian_2020', 'LUAD'),
        .('Lung_Qian_2020', 'LUSC'), # This study contains about half LUAD and half LUSC
        .('Lung_Xing_2021', 'LUAD'),
        .('lungcancer_Antonella_2020', 'LUAD'),
        .('lungcancer_Maynard_2020', 'LUAD'),
        .('lungcancer_Maynard_2020', 'LUSC'), # 45 LUAD and 1 LUSC
        .('Medulloblastoma_Hovestadt_2019', NA),
        .('Melanoma_JerbyArnon_2018', 'SKCM_metastatic'),
        .('Melanoma_JerbyArnon_2018', 'SKCM_primary'),
        .('Melanoma_Tirosh_2016', 'SKCM_metastatic'),
        .('Melanoma_Tirosh_2016', 'SKCM_primary'),
        .('MM_Cohen_2021', NA),
        .('MM_Ledergor_2018', NA),
        .('MM_Liu_2021', NA),
        .('Myeloproliferative_Nam_2019', NA),
        .('NasopharyngealCarcinoma_Chen_2020', 'HNSC'),
        .('NET_Unpublished', NA),
        .('Neuroblastoma_CellLine_Jansky_2021', NA),
        .('Neuroblastoma_Dong_2020', NA),
        .('Neuroblastoma_Jansky_2021', NA),
        .('Neuroblastoma_Kildisiute_2021', NA),
        .('Neuroblastoma_Mercatelli_2021', NA),
        .('OESOPHAGUS_Kinker_2020', 'ESCA_AC'),
        .('OESOPHAGUS_Kinker_2020', 'ESCA_ESCC'),
        .('OPSCC_Unpublished', 'HNSC'),
        .('Osteosarcoma_Zhou_2020', NA),
        .('Ovarian_Nath_2021', 'OV'),
        .('Ovarian_Olalekan_2021', 'OV'),
        .('Ovarian_Qian_2020', 'OV'),
        .('OVARY_Kinker_2020', 'OV'),
        .('PANCREAS_Kinker_2020', 'PAAD'),
        .('PDAC_Franses_2020', NA), # CTCs
        .('PDAC_Ligorio_2019', 'PAAD'),
        .('PDAC_Lin_2020', 'PAAD'),
        .('PDAC_Moncada_2020', 'PAAD'),
        .('PDAC_Peng_2019', 'PAAD'),
        .('PDAC_Steele_2020', 'PAAD'),
        .('PDAC_Yu_2012', 'PAAD'),
        .('PDAC_Yue_2020', 'PAAD'),
        .('Pituitary_Cui_2021', NA),
        .('PLEURA_Kinker_2020', NA),
        .('Prostate_Chen_2021', 'PRAD'),
        .('Prostate_Dong_2020', 'PRAD'),
        .('PROSTATE_Kinker_2020', 'PRAD'),
        .('Prostate_Miyamoto_2015', 'PRAD'),
        .('RCC_Bi_2021', 'KIRC'), # 7 KIRC and 1 KIRP
        .('RCC_Bi_2021', 'KIRP'),
        .('RCC_Obradovic_2021', 'KIRC'),
        .('RCC_Zhang_2021', 'KICH'), # 7 KIRC and 1 KICH
        .('RCC_Zhang_2021', 'KIRC'),
        .('SCHW_Unpublished', NA),
        .('SCLC_HumanMet_Ireland_2020', NA),
        .('SCLC_Mouse_Ireland_2020', NA),
        .('SKIN_Kinker_2020', 'SKCM_metastatic'),
        .('SKIN_Kinker_2020', 'SKCM_primary'),
        .('SkinSCC_Ji_2020', 'SKCM_primary'),
        .('SOFT_TISSUE_Kinker_2020', 'SARC'),
        .('STOMACH_Kinker_2020', 'STAD'),
        .('SyS_JerbyArnon_2021', 'SARC'),
        .('Thyroid_Gao_2021', 'THCA'),
        .('THYROID_Kinker_2020', 'THCA'),
        .('UPPER_AERODIGESTIVE_TRACT_Kinker_2020', 'HNSC'),
        .('URINARY_TRACT_Kinker_2020', 'BLCA'),
        .('WilmsTumor_Young_2018', NA)
    ))
]

fwrite(study_tcga_map, '../data/study_tcga_map.csv')
